Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,6 +38,9 @@ jobs:
     - name: Run bandit
       # there is no allow-failure yet. see https://github.com/actions/toolkit/issues/399
       run: bandit -r . || true
+    - name: Run bandit
+      # there is no allow-failure yet. see https://github.com/actions/toolkit/issues/399
+      run: safety || true
 
     - name: Test with pytest
       run: |
